/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `wurthco_crm2016` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `wurthco_crm2016`;

CREATE TABLE IF NOT EXISTS `llx_user` (
  `rowid` int(11) NOT NULL AUTO_INCREMENT,
  `entity` int(11) NOT NULL DEFAULT 1,
  `ref_ext` varchar(50) DEFAULT NULL,
  `ref_int` varchar(50) DEFAULT NULL,
  `employee` tinyint(4) DEFAULT 1,
  `fk_establishment` int(11) DEFAULT 0,
  `datec` datetime DEFAULT NULL,
  `tms` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `fk_user_creat` int(11) DEFAULT NULL,
  `fk_user_modif` int(11) DEFAULT NULL,
  `login` varchar(50) NOT NULL,
  `pass` varchar(128) DEFAULT NULL,
  `pass_crypted` varchar(128) DEFAULT NULL,
  `pass_temp` varchar(128) DEFAULT NULL,
  `api_key` varchar(128) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `civility` varchar(6) DEFAULT NULL,
  `lastname` varchar(50) DEFAULT NULL,
  `firstname` varchar(50) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `zip` varchar(25) DEFAULT NULL,
  `town` varchar(50) DEFAULT NULL,
  `fk_state` int(11) DEFAULT 0,
  `fk_country` int(11) DEFAULT 0,
  `job` varchar(128) DEFAULT NULL,
  `office_phone` varchar(20) DEFAULT NULL,
  `office_fax` varchar(20) DEFAULT NULL,
  `user_mobile` varchar(20) DEFAULT NULL,
  `personal_mobile` varchar(20) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `personal_email` varchar(255) DEFAULT NULL,
  `socialnetworks` varchar(255) DEFAULT NULL,
  `signature` varchar(255) DEFAULT NULL,
  `admin` smallint(6) DEFAULT 0,
  `module_comm` smallint(6) DEFAULT 1,
  `module_compta` smallint(6) DEFAULT 1,
  `fk_soc` int(11) DEFAULT NULL,
  `fk_socpeople` int(11) DEFAULT NULL,
  `fk_member` int(11) DEFAULT NULL,
  `fk_user` int(11) DEFAULT NULL,
  `fk_user_expense_validator` int(11) DEFAULT NULL,
  `fk_user_holiday_validator` int(11) DEFAULT NULL,
  `note` varchar(255) DEFAULT NULL,
  `datelastlogin` datetime DEFAULT NULL,
  `datepreviouslogin` datetime DEFAULT NULL,
  `egroupware_id` int(11) DEFAULT NULL,
  `ldap_sid` varchar(255) DEFAULT NULL,
  `openid` varchar(255) DEFAULT NULL,
  `statut` tinyint(4) DEFAULT 1,
  `photo` varchar(255) DEFAULT NULL,
  `lang` varchar(6) DEFAULT NULL,
  `color` varchar(6) DEFAULT NULL,
  `barcode` varchar(255) DEFAULT NULL,
  `fk_barcode_type` int(11) DEFAULT 0,
  `accountancy_code` varchar(32) DEFAULT NULL,
  `nb_holiday` int(11) DEFAULT 0,
  `thm` double(24,8) DEFAULT NULL,
  `tjm` double(24,8) DEFAULT NULL,
  `salary` double(24,8) DEFAULT NULL,
  `salaryextra` double(24,8) DEFAULT NULL,
  `weeklyhours` double(16,8) DEFAULT NULL,
  `note_public` varchar(255) DEFAULT NULL,
  `fk_vetado` int(11) DEFAULT 0,
  `fk_centrocosto` int(11) DEFAULT 3,
  `cuotavigente` int(11) DEFAULT 0,
  `fk_coachprueba` int(11) DEFAULT 0,
  `fk_coach` int(11) DEFAULT 0,
  `fk_gerencia` int(11) DEFAULT 0,
  `fk_division` int(11) DEFAULT 0,
  `dependientes` int(11) NOT NULL DEFAULT 0,
  `cuotadependientes` int(11) DEFAULT 0,
  `fecha_ingreso` date DEFAULT NULL,
  `fecha_retiro` date DEFAULT NULL,
  `bodega_cantidad` int(11) DEFAULT 0,
  `bodega_valor` int(11) DEFAULT 0,
  `titular_copa` int(11) DEFAULT 0,
  `id_partido` int(11) DEFAULT 0,
  `orsy_acomp` int(11) DEFAULT 0,
  `fk_back_office` int(11) DEFAULT 0,
  `estado` int(11) DEFAULT NULL,
  `etapa` int(11) DEFAULT NULL,
  `fecha_inicio_vta` date DEFAULT NULL,
  `fk_user_formador` int(11) DEFAULT NULL,
  `alias` varchar(20) DEFAULT NULL,
  `wn_number` varchar(20) DEFAULT NULL,
  `numero_zonas` int(11) DEFAULT 0,
  `estadovendedor` int(11) DEFAULT 0,
  `unegocio` smallint(3) NOT NULL DEFAULT 1,
  `canal_atencion` int(11) DEFAULT 0,
  `plan_carrera` int(11) DEFAULT 0,
  `dateemployment` datetime DEFAULT NULL,
  `birth` date DEFAULT NULL,
  `dateemploymentend` date DEFAULT NULL,
  `default_range` int(11) DEFAULT NULL,
  `default_c_exp_tax_cat` int(11) DEFAULT NULL,
  `import_key` varchar(14) DEFAULT NULL,
  `model_pdf` varchar(255) DEFAULT NULL,
  `pass_encoding` varchar(24) DEFAULT NULL,
  `fk_warehouse` int(11) DEFAULT NULL,
  `iplastlogin` varchar(250) DEFAULT NULL,
  `ippreviouslogin` varchar(250) DEFAULT NULL,
  `datelastpassvalidation` datetime DEFAULT NULL,
  `datestartvalidity` datetime DEFAULT NULL,
  `dateendvalidity` datetime DEFAULT NULL,
  `idpers1` varchar(128) DEFAULT NULL,
  `idpers2` varchar(128) DEFAULT NULL,
  `idpers3` varchar(128) DEFAULT NULL,
  `token_report` varchar(45) DEFAULT NULL,
  `asesor_kam` int(11) DEFAULT 0,
  `fecha_nacimiento` date DEFAULT NULL,
  `cupo_bono` double(24,8) DEFAULT 0.00000000,
  `nombre_firma` varchar(45) DEFAULT NULL,
  `usuario_comodin` int(11) DEFAULT 0,
  `division_zona` int(11) DEFAULT NULL,
  PRIMARY KEY (`rowid`),
  UNIQUE KEY `uk_user_login` (`login`,`entity`),
  UNIQUE KEY `uk_user_fk_socpeople` (`fk_socpeople`),
  UNIQUE KEY `uk_user_fk_member` (`fk_member`),
  UNIQUE KEY `uk_user_api_key` (`api_key`),
  KEY `idx_user_fk_societe` (`fk_soc`),
  KEY `idx_fk_coachprueba` (`fk_coachprueba`),
  KEY `idx_fk_coach` (`fk_coach`),
  KEY `idx_fk_gerencia` (`fk_gerencia`),
  KEY `idx_fk_division` (`fk_division`),
  KEY `fk_state` (`fk_state`),
  KEY `ind_unegocio` (`unegocio`),
  KEY `idx_lastname` (`lastname`),
  KEY `idx_firstname` (`firstname`),
  KEY `idx_tms` (`tms`),
  KEY `fk_country` (`fk_country`),
  KEY `fk_user_formador` (`fk_user_formador`),
  KEY `entity` (`entity`),
  KEY `fk_back_office` (`fk_back_office`),
  KEY `alias` (`alias`),
  KEY `canal_atencion` (`canal_atencion`),
  KEY `plan_carrera` (`plan_carrera`),
  KEY `token_report` (`token_report`)
) ENGINE=InnoDB AUTO_INCREMENT=1815 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `llx_user` (`rowid`, `entity`, `ref_ext`, `ref_int`, `employee`, `fk_establishment`, `datec`, `tms`, `fk_user_creat`, `fk_user_modif`, `login`, `pass`, `pass_crypted`, `pass_temp`, `api_key`, `gender`, `civility`, `lastname`, `firstname`, `address`, `zip`, `town`, `fk_state`, `fk_country`, `job`, `office_phone`, `office_fax`, `user_mobile`, `personal_mobile`, `email`, `personal_email`, `socialnetworks`, `signature`, `admin`, `module_comm`, `module_compta`, `fk_soc`, `fk_socpeople`, `fk_member`, `fk_user`, `fk_user_expense_validator`, `fk_user_holiday_validator`, `note`, `datelastlogin`, `datepreviouslogin`, `egroupware_id`, `ldap_sid`, `openid`, `statut`, `photo`, `lang`, `color`, `barcode`, `fk_barcode_type`, `accountancy_code`, `nb_holiday`, `thm`, `tjm`, `salary`, `salaryextra`, `weeklyhours`, `note_public`, `fk_vetado`, `fk_centrocosto`, `cuotavigente`, `fk_coachprueba`, `fk_coach`, `fk_gerencia`, `fk_division`, `dependientes`, `cuotadependientes`, `fecha_ingreso`, `fecha_retiro`, `bodega_cantidad`, `bodega_valor`, `titular_copa`, `id_partido`, `orsy_acomp`, `fk_back_office`, `estado`, `etapa`, `fecha_inicio_vta`, `fk_user_formador`, `alias`, `wn_number`, `numero_zonas`, `estadovendedor`, `unegocio`, `canal_atencion`, `plan_carrera`, `dateemployment`, `birth`, `dateemploymentend`, `default_range`, `default_c_exp_tax_cat`, `import_key`, `model_pdf`, `pass_encoding`, `fk_warehouse`, `iplastlogin`, `ippreviouslogin`, `datelastpassvalidation`, `datestartvalidity`, `dateendvalidity`, `idpers1`, `idpers2`, `idpers3`, `token_report`, `asesor_kam`, `fecha_nacimiento`, `cupo_bono`, `nombre_firma`, `usuario_comodin`, `division_zona`) VALUES
	(1810, 1, NULL, NULL, 1, 0, NULL, '2023-12-06 15:20:54', NULL, NULL, 'admin', '$2a$12$dI/lJZzwAYwTYYwTmjtG8./GTyDDSbFGxtadpJQkOY5MazEech9Am', NULL, NULL, NULL, NULL, NULL, 'Sinning', 'Ronaldo Aldair', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0.00000000, 'Administrador', 0, NULL),
	(1811, 1, NULL, NULL, 1, 0, NULL, '2023-12-06 15:19:48', NULL, NULL, 'monteroz', '$2a$12$bU3NFL7.4vcR1B7UVIHOu.nLw7KEslXoQe6cR3jrnxw9DLxbm/iai', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0.00000000, 'Ronaldo Aldair Sinning Montero', 0, NULL),
	(1812, 1, NULL, NULL, 1, 0, NULL, '2023-12-06 15:19:24', NULL, NULL, 'prueba1', '$2a$12$bU3NFL7.4vcR1B7UVIHOu.nLw7KEslXoQe6cR3jrnxw9DLxbm/iai', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0.00000000, NULL, 0, NULL),
	(1814, 1, NULL, NULL, 1, 0, NULL, '2024-01-04 18:29:52', NULL, NULL, 'montero', '$2y$10$ErVE8dgJlgMQl0O8WyO3uOsywJVM2lNny2/kqJ4xz8J67kD04lCcS', NULL, NULL, NULL, NULL, NULL, 'Sinning Montero', 'Ronaldo Aldair', 'Los almendros', NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'novedad7@gmail.com', NULL, NULL, 0, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 3, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, 1, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0.00000000, NULL, 0, NULL);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
